#! /bin/sh

#sxhkd &
panel &

bspc monitor DP1 -d V VI VII VIII
bspc monitor HDMI2 -d I II III IV



# window config
bspc config border_width            2
bspc config window_gap              12
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true
bspc config focused_border_color    '#1793D1'
bspc config pointer_modifier        mod1


# desktop rules and autostart
bspc rule -a Gimp desktop='^3' state=floating follow=on

bspc rule -a Firefox desktop='^5'
firefox &

bspc rule -a Screenkey manage=off

bspc rule -a stalonetray state=floating rectangle=5x5x1921x1
stalonetray &

bspc rule -a Pavucontrol desktop='^8'
pavucontrol &

bspc rule -a URxvt:cmus desktop='^8'
urxvt -name cmus -title cmus -e cmus &

bspc rule -a URxvt:mutt desktop='^7'
urxvt -name mutt -title mutt -e mutt &

bspc rule -a URxvt:vifm desktop='^1'
urxvt -name vifm -title vifm -e vifm &

bspc rule -a URxvt:term1 desktop='^1'
urxvt -name term1 &

bspc rule -a xterm:bashrun floating=true center=true

bspc desktop 0 --focus

