#! /bin/sh

#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" & 
#pgrep -x panel > /dev/null || panel &

#panel &
#panel01 &

#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" & 
#pgrep -x panel01 > /dev/null || panel01 &

rubypanel &

bspc monitor DP1 -d V VI VII VIII
bspc monitor HDMI2 -d I II III IV



# window config
bspc config -m HDMI2 top_padding    12
bspc config -m DP1 top_padding      12
bspc config border_width            2
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config click_to_focus          true
bspc config focused_border_color    '#1793D1'
bspc config pointer_modifier        mod1


# desktop rules and autostart
redshift-gtk -l 28.2:120.38 &

#start Chinese input
fcitx &

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Inkscape desktop='^4' state=floating follow=on

bspc rule -a Firefox desktop='^5'
firefox &

bspc rule -a Screenkey manage=off

bspc rule -a stalonetray state=floating rectangle=5x5+3000+1
stalonetray &

bspc rule -a Pavucontrol desktop='^8'
pavucontrol &

bspc rule -a Termite:cmus desktop='^8'
#urxvt -name cmus -title cmus -e cmus &

bspc rule -a Termite:neomutt desktop='^2'
bspc rule -a Termite:vifm desktop='^1'
bspc rule -a Termite:term1 desktop='^1'
bspc rule -a XTerm:* state=floating center=true rectangle=10x20

bspc desktop='^1' --focus
#tilix --new-process -t term1 --name term1 &
#tilix --new-process -t neomutt --name neomutt -e neomutt &
#tilix --new-process -t vifm --name vifm -e vifm &
#tilix --new-process -t cmus --name cmus -e cmus &
termite --name term1 &
termite --name neomutt -e neomutt &
termite --name vifm -e vifm &
termite --name cmus -e cmus &
